### ISSUE TITLE
[MILESTONE] Toevoegen bestellen

### ISSUE THREAD

**Issue by Zeegeuze** [Zeegeuze/artistine#54]
- [ ] Nieuwe database: order + order_item

- [ ] Nieuwe kolom bij artwork: amount

- [ ] Link toevoegen aan betaalmandje (+ aantal? of in betaalmandje?)

- [ ] user pagina aanmaken

- [ ] Pagina betaalmandje:
  - opgelet: enkel ingelogde user
  - tekstvak voor uitleg (kleur / naam etc)
  - aantal items beschikbaar
  - aantal items te bestellen (keuze met max aantal beschikbare items)
  - link voor toevoegen extra amount -> direct beschikbare items anders tonen (niet aanpassen in systeem om verlaten mandjes te omzeilen / eventueel 5 minuten vast houden)
  - aantal dubbel checken voor bestellen (beschikbaarheid)

- [ ] Voorzien betaalcode om betalingen terug te vinden

- [ ] Wat met groepen van bijvoorbeeld verschillende kleuren?
